version: "3"
services:
  axon-server:
    image: axoniq/axonserver:latest
    ports:
      - "8024:8024"
      - "8124:8124"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: springbankRootPsw